In [ ]:
!pip install rpy2
!conda install r-ggplot2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: rpy2 in c:\users\logan\appdata\roaming\python\python311\site-packages (3.5.16)
Requirement already satisfied: cffi>=1.15.1 in c:\programdata\miniconda3\lib\site-packages (from rpy2) (1.16.0)
Requirement already satisfied: jinja2 in c:\users\logan\appdata\roaming\python\python311\site-packages (from rpy2) (3.1.3)
Requirement already satisfied: tzlocal in c:\users\logan\appdata\roaming\python\python311\site-packages (from rpy2) (5.2)
Requirement already satisfied: packaging in c:\users\logan\appdata\roaming\python\python311\site-packages (from rpy2) (24.0)
Requirement already satisfied: pycparser in c:\programdata\miniconda3\lib\site-packages (from cffi>=1.15.1->rpy2) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\logan\appdata\roaming\python\python311\site-packages (from jinja2->rpy2) (2.1.5)
Requirement already satisfied: tzdata in c:\users\logan\appdata\roaming\python\python311\site-packages (from tzlocal->rpy2) (2024.1)

In [13]:
import rpy2
import os
os.environ['R_HOME'] = 'C:\Program Files\R\R-4.3.2'
import rpy2.robjects as robjects
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr, data

In [3]:
utils = importr('utils')
base = importr('base')

In [4]:
utils.install_packages("amerifluxr")

R[write to console]: Installing package into 'C:/Users/Logan/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)

--- Please select a CRAN mirror for use in this session ---

R[write to console]: trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.3/amerifluxr_1.0.0.zip'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 497151 bytes (485 KB)

R[write to console]: downloaded 485 KB

package 'amerifluxr' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Logan\AppData\Local\Temp\Rtmpi8FDmt\downloaded_packages

<rpy2.rinterface_lib.sexp.NULLType object at 0x00000292213D55D0> [0]

In [6]:
amr = importr('amerifluxr')

In [59]:
sites = amr.amf_site_info()

In [60]:
sites
with (robjects.default_converter + pandas2ri.converter).context():
  pd_from_r_df = robjects.conversion.get_conversion().rpy2py(r_df)

pd_from_r_df

,SITE_ID,SITE_NAME,COUNTRY,STATE,IGBP,TOWER_BEGAN,TOWER_END,URL_AMERIFLUX,LOCATION_LAT,LOCATION_LONG,LOCATION_ELEV,CLIMATE_KOEPPEN,MAT,MAP,DATA_POLICY,DATA_START,DATA_END
1,AR-Bal,Balcarce BA,Argentina,Buenos Aires,CRO,2012,2013,https://ameriflux.lbl.gov/sites/siteinfo/AR-Bal,-37.7596,-58.3024,130.0,Cfb,14.0,926.00,LEGACY,2012,2013
2,AR-CCa,Carlos Casares agriculture,Argentina,Buenos Aires,CRO,2012,NA_character_,https://ameriflux.lbl.gov/sites/siteinfo/AR-CCa,-35.6210,-61.3181,83.0,Cfa,16.1,1060.00,CCBY4.0,2012,2020
3,AR-CCg,Carlos Casares grassland,Argentina,Buenos Aires,GRA,2018,NA_character_,https://ameriflux.lbl.gov/sites/siteinfo/AR-CCg,-35.9244,-61.1855,84.0,Cfa,16.1,1060.00,CCBY4.0,2018,2020
4,AR-Cel,CELPA Mar Chiquita BA,Argentina,Buenos Aires,WET,2018,2018,https://ameriflux.lbl.gov/sites/siteinfo/AR-Cel,-37.7028,-57.4192,1.0,Cfb,14.0,926.00,LEGACY,2018,2018
5,AR-Rom,Romano Mar Chiquita BA,Argentina,Buenos Aires,WET,2014,2015,https://ameriflux.lbl.gov/sites/siteinfo/AR-Rom,-37.5508,-57.2972,1.0,Cfb,14.0,926.00,LEGACY,2014,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,US-xYE,NEON Yellowstone Northern Range (Frog Rock) (Y...,USA,WY,ENF,2018,NA_character_,https://ameriflux.lbl.gov/sites/siteinfo/US-xYE,44.9535,-110.5391,2116.0,Dfc,3.4,493.44,CCBY4.0,2018,2022
658,US-YK1,"Yukon-Kuskokwim Delta, Izaviknek-Kingaglia upl...",USA,AK,WET,2019,NA_character_,https://ameriflux.lbl.gov/sites/siteinfo/US-YK1,61.2723,-163.2228,15.0,NA_character_,NaN,NaN,CCBY4.0,2019,2022
659,US-YK2,"Yukon-Kuskokwim Delta, Izaviknek-Kingaglia upl...",USA,AK,WET,2019,NA_character_,https://ameriflux.lbl.gov/sites/siteinfo/US-YK2,61.2548,-163.2590,15.0,NA_character_,NaN,NaN,CCBY4.0,2019,2022
660,US-Ylw,Yellow Cab urban,USA,TX,URB,2007,2013,https://ameriflux.lbl.gov/sites/siteinfo/US-Ylw,29.7894,-95.3536,14.0,Cfa,20.0,1260.00,LEGACY,-2147483648,-2147483648
661,US-YNS,North Star Yedoma,USA,AK,GRA,2021,NA_character_,https://ameriflux.lbl.gov/sites/siteinfo/US-YNS,64.8939,-147.6374,186.9,Dfc,-2.5,275.00,LEGACY,-2147483648,-2147483648

In [41]:
bif_path = amr.amf_download_bif(user_id = "logangall",
              user_email = "gall0487@umn.edu",
              data_policy = "CCBY4.0",
              agree_policy = True,
              intended_use = "synthesis",
              intended_use_text = "obtain AmeriFlux sites' geolocation, IGBP, and climate classification",
              verbose = True,
              out_dir = r"C:\Users\Logan\Desktop\School Files\GIS 8990 Project Zero\project_zero\ETL_Management\AMF_DATA",                  
              site_w_data = True)

Data use guidelines for AmeriFlux CC-BY-4.0 Data Policy:

(1) Data user is free to Share (copy and redistribute the material in any medium or format) and/or Adapt (remix, transform, and build upon the material) for any purpose.
(2) Provide a citation to each site data product that includes the data-product DOI and/or recommended publication.
(3) Acknowledge funding for supporting AmeriFlux data portal: U.S. Department of Energy Office of Science.

R[write to console]: trying URL 'https://ftp.fluxdata.org/.ameriflux_downloads/BADM-SGI/AMF_AA-Flx_BIF_CCBY4_20240410.xlsx?=logangall'

R[write to console]: Content type 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
R[write to console]:  length 2728434 bytes (2.6 MB)

R[write to console]: downloaded 2.6 MB

In [30]:
data = amr.amf_read_bif(file = bif_path)
with (robjects.default_converter + pandas2ri.converter).context():
  pd_from_r_df = robjects.conversion.get_conversion().rpy2py(data)

pd_from_r_df

R[write to console]:
R[write to console]: -
R[write to console]:
R[write to console]: |

R[write to console]:
R[write to console]:
R[write to console]: /

R[write to console]:
R[write to console]:
R[write to console]: -
R[write to console]:
R[write to console]: /

R[write to console]:

,SITE_ID,GROUP_ID,VARIABLE_GROUP,VARIABLE,DATAVALUE
1,AR-CCa,98388,GRP_ACKNOWLEDGEMENT,ACKNOWLEDGEMENT,Acknowledge Los Grobo and the AmeriFlux Manage...
2,AR-CCa,98392,GRP_CLIM_AVG,MAT,16.1
3,AR-CCa,98392,GRP_CLIM_AVG,MAP,1060
4,AR-CCa,98392,GRP_CLIM_AVG,CLIMATE_KOEPPEN,Cfa
5,AR-CCa,27001205,GRP_COUNTRY,COUNTRY,Argentina
...,...,...,...,...,...
104710,US-YK2,103497,GRP_TOWER_POWER,TOWER_POWER,Methanol generator
104711,US-YK2,98624,GRP_TOWER_POWER,TOWER_POWER,Solar panels
104712,US-YK2,24001209,GRP_URL_AMERIFLUX,URL_AMERIFLUX,https://ameriflux.lbl.gov/sites/siteinfo/US-YK2
104713,US-YK2,98621,GRP_UTC_OFFSET,UTC_OFFSET,-9
104714,US-YK2,98621,GRP_UTC_OFFSET,UTC_OFFSET_DATE_START,201909281700

In [34]:
data_aval = amr.amf_list_data(site_set = ['US-Ro4', 'US-Ro3'])
data_aval

<rpy2.robjects.vectors.DataFrame object at 0x000002924AF316D0> [19]
R classes: ('data.frame',)
[StrSexpVe..., StrSexpVe..., StrSexpVe..., BoolSexpV..., ..., FloatSexp..., FloatSexp..., FloatSexp..., FloatSexp...]
  SITE_ID: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x000002924AF33950> [16]
R classes: ('character',)
['US-Ro3', 'US-Ro3', 'US-Ro3', 'US-Ro3', ..., 'US-Ro4', 'US-Ro4', 'US-Ro4', 'US-Ro4']
  VARIABLE: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x000002924AEBE610> [16]
R classes: ('character',)
['CO2', 'FC', 'G', 'H', ..., 'VPD_PI', 'WD', 'WS', 'ZL']
  BASENAME: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x000002924AEBF490> [16]
R classes: ('character',)
['CO2', 'FC', 'G', 'H', ..., 'VPD', 'WD', 'WS', 'ZL']
  GAP_FILLED: <class 'rpy2.robjects.vectors.BoolVector'>
  <rpy2.robjects.vectors.BoolVector object at 0x000002924AEBD710> [10]
R classes: ('logical',)
[       0,        0,        0,        0, ...,        0,        0,        0,        0]
...
  Y1991: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x000002924AEBD790> [14]
R classes: ('numeric',)
[0.000000, 0.000000, 0.000000, 0.000000, ..., 0.997032, 0.981221, 0.980080, 0.664897]
  Y1992: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x000002924AEBF550> [14]
R classes: ('numeric',)
[0.000000, 0.000000, 0.000000, 0.000000, ..., 0.975856, 0.957477, 0.957363, 0.648288]
  Y1993: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x000002924AF2FA10> [14]
R classes: ('numeric',)
[0.000000, 0.000000, 0.000000, 0.000000, ..., 0.999772, 0.988242, 0.986644, 0.709304]
  Y1994: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x000002924AF2E450> [14]
R classes: ('numeric',)
[0.000000, 0.000000, 0.000000, 0.000000, ..., 0.000000, 0.000000, 0.000000, 0.000000]

In [42]:
bif_path = amr.amf_download_base(user_id = "logangall",
                  user_email = "gall0487@umn.edu",
                  site_id = ['US-Ro4', 'US-Ro3'],
                  data_product = "BASE-BADM",
                  data_policy = "CCBY4.0",
                  agree_policy = True,
                  intended_use = "synthesis",
                  intended_use_text = "testing download functionality of amerifluxr API",
                  verbose = True,
                  out_dir = r"C:\Users\Logan\Desktop\School Files\GIS 8990 Project Zero\project_zero\ETL_Management\AMF_DATA")

Data use guidelines for AmeriFlux CC-BY-4.0 Data Policy:

(1) Data user is free to Share (copy and redistribute the material in any medium or format) and/or Adapt (remix, transform, and build upon the material) for any purpose.
(2) Provide a citation to each site data product that includes the data-product DOI and/or recommended publication.
(3) Acknowledge funding for supporting AmeriFlux data portal: U.S. Department of Energy Office of Science.

R[write to console]: trying URL 'https://ftp.fluxdata.org/.ameriflux_downloads/BASE-BADM/AMF_US-Ro3_BASE-BADM_4-5.zip?=logangall'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 4493374 bytes (4.3 MB)

R[write to console]: downloaded 4.3 MB


R[write to console]: trying URL 'https://ftp.fluxdata.org/.ameriflux_downloads/BASE-BADM/AMF_US-Ro4_BASE-BADM_23-5.zip?=logangall'

R[write to console]: Content type 'application/zip'
R[write to console]:  length 21826164 bytes (20.8 MB)

R[write to console]: downloaded 20.8 MB

In [58]:
datasets = []
for i in bif_path:
    new_dat = amr.amf_read_base(file = i, unzip = True, parse_timestamp = True)
    with (robjects.default_converter + pandas2ri.converter).context():
        new_dat = robjects.conversion.get_conversion().rpy2py(new_dat)
    datasets.append(new_dat)

R[write to console]: Error in (function (file)  : File extention not valid...

RRuntimeError: Error in (function (file)  : File extention not valid...

In [54]:
datasets[0]['TIMESTAMP']

1       2004-01-01 00:15:00+00:00
2       2004-01-01 00:45:00+00:00
3       2004-01-01 01:15:00+00:00
4       2004-01-01 01:45:00+00:00
5       2004-01-01 02:15:00+00:00
                   ...
70124   2007-12-31 21:45:00+00:00
70125   2007-12-31 22:15:00+00:00
70126   2007-12-31 22:45:00+00:00
70127   2007-12-31 23:15:00+00:00
70128   2007-12-31 23:45:00+00:00
Name: TIMESTAMP, Length: 70128, dtype: datetime64[ns, GMT]

In [56]:
import pandas as pd
new_df = pd.DataFrame()